
export const ADD_CATEGORY="ADD_CATEGORY"

export const GET_CATEGORIES="GET_CATEGORIES";

export const GET_CATEGORY="GET_CATEGORY";

export const UPDATE_CATEGORY="UPDATE_CATEGORY";

export const DELETE_CATEGORY="DELETE_CATEGORY";

export const LOAD_CATEGORY="LOAD_CATEGORY";

export const FAIL_CATEGORY="FAIL_CATEGORY";