
export const GET_RESTAURANT="GET_RESTAURANT";

export const UPDATE_RESTAURANT="UPDATE_RESTAURANT";


export const ADD_RESTAURANT="ADD_RESTAURANT";

export const LOAD_RESTAURANT="LOAD_RESTAURANT";

export const FAIL_RESTAURANT="FAIL_RESTAURANT";